### ISSUE TITLE
Consolidate Redundant Favorite Models

### ISSUE THREAD

**Issue by sunr4y** [Daily-Projects-Server/virtual-marketplace#75]
We currently have two nearly identical `Favorite` models in our project, one in the `listings` app and another in the `users` app. This redundancy can lead to confusion, maintenance issues, and potential inconsistencies in our data model. We need to consolidate these models into a single `Favorite` model to improve code clarity and maintainability.

## Current Situation
- `listings/models.py` has a `Favorite` model
- `users/models.py` has a `Favorite` model
- Both models have similar structure and purpose

## Proposed Solution
1. Keep the `Favorite` model in the `listings` app, as it's more closely related to listings functionality.
2. Remove the `Favorite` model from the `users` app.
3. Update all references to use the consolidated `Favorite` model from `listings`.

## Tasks
- [ ] Consolidate the `Favorite` model in `listings/models.py`:
  ```python
  from django.db import models
  from django.contrib.auth import get_user_model

  User = get_user_model()

  class Favorite(models.Model):
      user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='favorites')
      listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name='favorited_by')

      class Meta:
          unique_together = ('user', 'listing')
  ```
- [ ] Remove the `Favorite` model from `users/models.py`
- [ ] Update imports in all relevant files to use `from listings.models import Favorite`
- [ ] Update views in `listings/views/favorite_views.py` to use the consolidated model
- [ ] Create and run migrations to remove the redundant model and update the database schema
- [ ] Update any serializers that reference the `Favorite` model
- [ ] Update tests to reflect the changes in the model structure
- [ ] Verify that all functionality related to favorites still works as expected

## Files to be Modified
- `virtual-marketplace/backend/listings/models.py`
- `virtual-marketplace/backend/users/models.py`
- `virtual-marketplace/backend/listings/views/favorite_views.py` (Currently being refactored)
- Any other files that import or use the `Favorite` model

## Acceptance Criteria
- [ ] Only one `Favorite` model exists in the project
- [ ] All favorite-related functionality works as expected
- [ ] No references to the old `Favorite` model in `users` app remain
- [ ] Database schema is updated correctly
- [ ] All tests pass after the changes
